---
title: "case_study_2"
author: "Ghizlane Zerouali and Samira Zarandioon"
date: "April 21, 2017"
output:
  word_document: default
  pdf_document: default
---

# Question 1

## SAS code:

```
proc iml;
reset print;
A={4 5 1 2, 1 0 3 5, 2 1 8 2};
quit;
```
Output:

A 3 rows 4 cols (numeric)

4	5	1	2
1	0	3	5
2	1	8	2

## R code:

```{r}
mymat = matrix(c(4,5,1,2,1,0,3,5,2,1,8,2), ncol = 4, byrow = TRUE)
mymat
```


## Python Code:

```{python}
import numpy as np
a = np.matrix('4 5 1 2; 1 0 3 5; 2 1 8 2')
print(a)
```

# Question 2

```{r}
#install.packages("tseries")
library(tseries)
XOMData <- get.hist.quote("xom", quote = "Close")

XOMret <- log(lag(XOMData)) - log(XOMData)

XOMVol <- sd(XOMret) * sqrt(250)* 100

## volatility get
getVol <- function(d, logrets) {
      var = 0
      lam = 0
      varlist <- c()
      for (r in logrets) {
        if (! is.na(r)) {
          lam = lam*(1-1/d)+1
          var=(1-1/lam)*var+(1/lam)*r^2
          varlist <- c(varlist, var)
        }
      }
      sqrt(varlist)
}

volest <- getVol(10,XOMret)
volest2 <- getVol(30,XOMret)
volest3 <- getVol(100,XOMret)

plot(volest, type="l")
lines(volest2, type="l", col="yellow")
lines(volest3, type="l", col="Red")

```

# Question 3
## a
```{r}
#install.packages("dplyr")
library(dplyr)
orange_grouped <- group_by(Orange, Tree)
summarise(orange_grouped, mean=mean(circumference), median=median(circumference))
```

## b
```{r}
plot(Orange$age, Orange$circumference, xlab="age", ylab = "circumfence")
```
## c
```{r}
boxplot(Orange$circumference ~ Orange$Tree)
```

# Question 05

```{r}
t<-seq(0,10,length=1000)
x<-sqrt(t)*cos(2*pi*t)
y<-sqrt(t)*sin(2*pi*t)
plot(x,y,axes=F,type="l",lwd=3,xlab="x(t)",ylab="y(t)",col="red")
axis(1,at=seq(-3,3,by=0.5),labels=seq(-3,3,by=0.5))
axis(2)
box()
title(main=expression(
paste("(x(t),y(t)) with polar coordinates", (list(sqrt(t),2*pi*t))
)))
```